# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b22956fd6c9fcc36cb5915d52076a53cd980839014f55bfb898af221fcc096df92d87eee95566d85f69049357d1bb6e528252f7e133bacec55cb2a43f5bc297

test:
  secret_key_base: 4530fbba3582d2599fb464fe4509218672ea5594f294a505816ba776e5a6a363faa7ac826cd160cf152a11fe16fa19b70b6488f88a7b05ea052eafd95b3bf4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
